---
title: "Co-curricular"
---
  

I do like swimming, chess, photography, and soccer  
Me gusta la natación, el ajedrez, la fotografía y el fútbol


**Activities/Actividades**  

1. Treasurer, Plant Pathology Graduate Student Club  of UNL/Tesorero del club de fitopatología de los estudiantes de grado de UNL, 2018-2019
2. Secretary, Plant Pathology Graduate Student Club of UNL/Secretario del club de fitopatología de los estudiantes de grado de UNL, 2017-2018  
3. Reviewed applications for Bursary Assistance Awards for ICPP 2018/Revisión de las aplicaciones de Bursary Assistance Awards del ICPP 2018
4. Member at Plant Pathology Graduate Student Club of UNL/Miembro del club de fitopatología de los estudiantes de grado de UNL | 2016-PRESENT
5. Member of Toastmasters International; EC Speakers Toastmasters Club UNL/Miembro de Toastmasters International; Club EC Speakers Toastmasters UNL | 2019-Present
6. Member at Mexican American Student Association of UNL/Miembro de la Asociación de estudiantes México-Americanos de UNL | 2017-2018  
7. Volunteer in several events in Rotary Mexico-Texcoco de Gante, Mexico State/Voluntario en varios eventos de Rotary México -Texcoco de Gante, Estado de México,  2015-2016  

**Certifications/Certificaciones** 

Lifeguarding and water safety by American Red Cross/Salvavidas y Seguridad en el Agua por la Asociación Americana de Cruz Roja

