---
title: " Diseases Notes"
---
  
# Diseases Notes
# Notas de Enfermedades
  
***corresponding author**  

García-Ruiz, M. T., Galicia-Buendia, N. G., Leyva-Mir, S. G., Camacho-Tapia, M., C. Correia, K., **Nieto-López, E. H.**, & Tovar-Pedraza, J. M. 2019. First Report of Powdery Mildew of European Plum Caused by _Podosphaera tridactyla_ in Mexico.Plant Disease. DOI: https://doi.org/10.1094/PDIS-08-18-1371-PDN  

Alvarado-Rosales, D., **Nieto-Lopez, E. H.***, Ayala-Escobar, V., Teliz-Ortiz,D., Nieto-Angel, R., and Tovar-Pedraza, J. M. 2018. First Report of _Gymnosporangium globosum_ on _Crataegus gracilior_ in Mexico. Plant Disease.
First look. DOI: https://apsjournals.apsnet.org/doi/10.1094/PDIS-02-18-
0246-PDN

**Nieto-Lopez, E. H.**, Everhart, S.E., Ayala-Escobar, V., Camacho-Tapia, M., Bernardi-Lima, Nelson, Nieto-Angel, R., and Tovar-Pedraza, J. M. 2018. First Report of _Colletotrichum gloeosporioides_ Causing Anthracnose of
Tejocote _Crataegus gracilior_ Fruits in Mexico. Plant Disease. First look.
DOI: https://doi.org/10.1094/PDIS-02-18-0233-PDN

Solano-Baez, A. R., Jimenez-Jimenez, B., Camacho-Tapia, M., Leyva-Mir,S. G., **Nieto-Lopez, E. H.**, and Tovar-Pedraza, J. M. 2017. First confirmed
report of _Cerotelium fici_ causing leaf rust on _Ficus carica_ in Mexico. Plant Pathology & Quarantine. DOI:
http://www.plantpathologyquarantine.org/pdf/PPQ_7_2_9.pdf


Tovar-Pedraza, J. M., Leyva-Mir, S. G., Camacho-Tapia, M., **Nieto-Lopez, E. H.**, Ayala-Escobar, V., and Garcia-Leon, E. 2016. First Report of Powdery Mildew Caused by _Erysiphe heraclei_ on _Hedera helix_ in Mexico.
Plant Disease 02/2016; 100(4):647., DOI:
https://apsjournals.apsnet.org/doi/abs/10.1094/PDIS-09-15-1030-PDN

Tovar-Pedraza, J. M., Leyva-Mir, S. G., **Nieto-Lopez, E. H.**, Nava-Diaz, C., Goodwin, P. H., H. Rosas-Saito, G. 2016. First Report of Powdery Mildew Caused by _Erysiphe heraclei_ on _Ammi majus_ in Mexico. Plant Disease
01/2016; 100(3):647., DOI:
https://apsjournals.apsnet.org/doi/abs/10.1094/PDIS-06-15-0716-PDN

**Nieto-Lopez, E. H.**, Leyva-Mir, S. G., Ayala-Escobar, V., Nava-Diaz, C., and Tovar-Pedraza, J. M. 2016. First Report of Powdery Mildew caused by
_Erysiphe alphitoides_ on _Quercus rugosa_ in Mexico. Journal of Plant Pathology:
12/2015; 97(3):549.DOI:
http://www.sipav.org/main/jpp/index.php/jpp/article/view/3400

Alvarado-Rosales, D., **Nieto-Lopez, E. H.***, Teliz-Ortiz, D., Ayala-Escobar,V., Silva-Rojas, H. V., Nieto-Angel, R., Leyva-Mir, S. G., Jimenez-Nieto, A., and Mendez-Inocencio, C. 2015. First report of _Gymnosporangium clavipes_
affecting _Crataegus mexicana_ var. Chapeado and C. gracilior in Mexico.Research in Plant Disease 08/2015; 21(3):250-252., DOI: http://www.online-
rpd.org/journal/view.html?uid=1462&&vmd=Full;

**Nieto-Lopez, E.H.**, Aguilar-Perez, L. A., Ayala-Escobar, V., Nieto-Angel,D., Nieto-Angel R., Leyva-Mir, S. G., and Tovar-Pedraza, J. M. 2014. First
report of _Botrytis cinerea_ causing postharvest gray mold of tejocote
_Crataegus mexicana_ fruit in Mexico. Journal of Plant Pathology 10/2014;
96(4):124., DOI:
http://www.sipav.org/main/jpp/index.php/jpp/article/view/3207

