---
title: "Research"
---
  
# Research
# Investigación
  
My current research focus on the study of risk of fungicide resistance emergence in [_Sclerotinia sclerotiorum_](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1364-3703.2005.00316.x)
known as white mold, a fungal pathogen that causes disease outbreaks on soybean. Keen, the aims are  to determine fungicide sensitivity of populations from soybean; evaluate the effect of different fungicide applications on the sensitivity of field populations; and characterize the population structure and genetic diversity populations from soybean throughout the North Central United States and Mexico./ Mi actual investigación está enfocada en el estudio del riesgo a la emergencia de la resistencia a fungicidas por [_Sclerotinia sclerotiorum_](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1364-3703.2005.00316.x)  conocido como moho blanco, un hongo fitopatógeno que causa enfermedad en soya. Los objetivos son, determinar la sensibilidad a fungicidas de poblaciones de soya; evaluar el efecto de diferentes aplicaciones de fungicidas en la sensibilidad de la poblaciones directamente en el campo; y caracterizar la estructura poblacional y diversidad genética de poblaciones de soya dentro Estados Unidos central y México  

My thesis title is "Fungicide Sensitivity and Population Structure of _Sclerotinia sclerotiorum_ from Soybean in
the North Central United States and Dry Bean
in Mexico"/ El título de mi tesis es  "Sensibilidad a fungicidas y estructura poblacional de _Sclerotinia sclerotiorum_ de soya en Estados Unidos central y de fríjol en México".